version: '3.8'

services:
  backend:
    image: backend-project
    build:
      context: ../exercise_03/example-backend
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REQUEST_ORIGIN=http://localhost
    container_name: backend
    depends_on:
      - db

  frontend:
    image: frontend-project
    build:
      context: ../exercise_03/example-frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost/api
    ports:
      - 1000:5000
    container_name: frontend
    depends_on:
      - backend
  
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped    
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    container_name: nginx

