version: '3.8'

services:
  backend:
    image: backend-project
    build: ../../part_1/exercise_13/
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REQUEST_ORIGIN: http://frontend:1000/ # Changed
    container_name: backend
    depends_on:
      - db
      - redis

  frontend:
    image: frontend-project
    build: ../../part_1/exercise_12/
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080/ # Changed
  
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped    
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx

