version: '3.8'

services:
  backend:
    image: backend-project
    build: ../../part_1/exercise_13/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: backend
    depends_on:
      - db

  frontend:
    image: frontend-project
    build: ../../part_1/exercise_12/
    ports:
      - 1000:1000
    container_name: frontend
  
  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped    
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

