version: '3.8'

services:
  backend:
    image: backend-project
    ports:
      - 8080:8080
    container_name: backend
  
  frontend:
    image: frontend-project
    ports:
      - 1000:1000
    container_name: frontend

