FROM golang:1.22.1-bullseye

WORKDIR /app

COPY . /app

RUN apt-get update && \
    apt-get install -y gcc musl-dev && \
    useradd -m appuser && \
    chown -R appuser:appuser /app && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER appuser

ENV REQUEST_ORIGIN=http://localhost:1000 PORT=8080
EXPOSE $PORT

RUN go build && \
    go test ./...

CMD ./server