FROM golang:1.16.15-alpine3.15

WORKDIR /app

COPY . /app

# Install build dependencies
# gcc and musl-dev are typically required for go test
RUN apk add --no-cache gcc musl-dev

# --- Additional for Exercise 1.14
ENV REQUEST_ORIGIN=http://localhost:1000
# --- End

ENV PORT=8080
EXPOSE $PORT

RUN go build
RUN go test ./...

CMD ./server