version: '3.8'

services:
  backend:
    image: backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend

  frontend:
    image: frontend-project
    ports:
      - 1000:1000
    container_name: frontend
  
  redis:
    image: redis:alpine
    container_name: redis
