version: '3.8'

services:
  backend:
    image: backend-project
    build: 
      context: ../exercise_03/example-backend
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend

  frontend:
    image: frontend-project
    build: 
      context: ../exercise_03/example-frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:8080
    ports:
      - 1000:5000
    container_name: frontend
  
  redis:
    image: redis:alpine
    container_name: redis